version: 0.2

phases:
  install:
    commands:
      - pip install -r autoload/requirements.txt -t autoload

artifacts:
  base-directory: autoload
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
