version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r bom-create-database/requirements.txt -t bom-create-database

artifacts:
  base-directory: bom-create-database
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
