version: 0.2

phases:
  install:
    commands:
      - pip install -r bom-partition/requirements.txt -t bom-partition

artifacts:
  base-directory: bom-partition
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
